# Hospital Readmissions Analysis Using Logistic Regression
The objective of this project is to analyze and predict hospital readmissions by evaluating patient data such as diagnoses, medication use, length of stay, and treatment history. The dataset undergoes comprehensive preprocessing, including handling missing values, encoding categorical features, and standardizing numerical variables to enhance model performance. Logistic Regression serves as the core modeling approach, with evaluation metrics such as accuracy, precision, recall, and AUC-ROC used to measure its effectiveness. Hyperparameter tuning is conducted using tools like GridSearchCV to improve model robustness. This project aims to support healthcare providers in identifying at-risk patients, optimizing treatment plans, and reducing unnecessary hospital readmissions for better resource management and patient care.

 ## 📌 1: Load Data & Import Required Libraries

* **pandas**: Used for data manipulation and analysis, offering powerful data structures like DataFrames to handle and process structured data efficiently.
* **numpy**: Provides support for numerical operations on large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.
* **matplotlib.pyplot**: Used for creating static, interactive, and animated visualizations in Python, enabling plotting of various graphs such as line charts, scatter plots, and histograms.
* **seaborn**: A data visualization library built on matplotlib, providing a high-level interface to create statistical graphics such as heatmaps, pair plots, and box plots.
* **sklearn.linear_model**: scikit-learn is a machine learning library used for model building, preprocessing, and evaluation.
* **sklearn.preprocessing**:
  * **StandardScaler**: Standardizes features by removing the mean and scaling to unit variance, ensuring all features contribute equally to the model.
  * **OneHotEncoder**: Converts categorical variables into a binary matrix (dummy variables), enabling models to interpret non-numerical features.
  * **LabelEncoder**: Encodes categorical labels as integers.
  * **LogisticRegression**: It's used for binary or multiclass classification problems.
* **sklearn.metrics**:
  * **accuracy_score**: Measures model accuracy.
  * **classification_report**: Generates a detailed report of classification metrics.
  * **confusion_matrix**: Creates a confusion matrix.
  * **roc_curve & auc**: Plots the Receiver Operating Characteristic (ROC) curve.
                         Computes the Area Under the Curve (AUC) score.
  * **ConfusionMatrixDisplay**: Visualizes the confusion matrix.
  * **mean_absolute_error**: Measures the mean absolute error for regression models.
  * **mean_squared_error**: Computes the mean squared error for regression models.
  * **r2_score**: Determines the R-squared value for regression models.
* **sklearn.model_selection**:
  * **train_test_split**: Splits your dataset into training and testing subsets.
  * **GridSearchCV**: Implements Grid Search for hyperparameter optimization.

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression  # oR from sklearn import linear_model
import matplotlib.pyplot as plt # plyplot because it support pythonplot too
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix, ConfusionMatrixDisplay,mean_absolute_error, mean_squared_error,r2_score, roc_curve, auc
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder , StandardScaler,  LabelEncoder
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv(r"C:\Users\Sarita Safare\Downloads\PGA 32 - PYTHON\hospital_readmissions_sample_3000.csv")
df

,Patient_ID,Age,Gender,Admission_Type,Primary_Diagnosis,Length_of_Stay,Previous_Admissions,Comorbidities,Discharge_Disposition,Readmitted
0,10001,71,Male,Urgent,Pneumonia,4,5,3-4,Transferred,No
1,10002,34,Male,Emergency,Diabetes,21,8,NaN,Home,No
2,10003,80,Female,Urgent,Pneumonia,21,1,1-2,Transferred,No
3,10004,40,Female,Emergency,Pneumonia,8,2,1-2,Home,No
4,10005,43,Male,Elective,Stroke,25,8,5+,Transferred,No
...,...,...,...,...,...,...,...,...,...,...
2995,12996,68,Female,Urgent,Cancer,20,4,1-2,Expired,No
2996,12997,73,Male,Urgent,Heart Failure,15,7,1-2,Expired,No
2997,12998,29,Male,Urgent,Heart Failure,1,3,NaN,Expired,No
2998,12999,72,Male,Urgent,Diabetes,2,3,NaN,Expired,No
2999,13000,63,Male,Urgent,Pneumonia,8,6,NaN,Expired,No

## 🔍 2. Data Preprocessing

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Patient_ID             3000 non-null   int64
 1   Age                    3000 non-null   int64
 2   Gender                 3000 non-null   object
 3   Admission_Type         3000 non-null   object
 4   Primary_Diagnosis      3000 non-null   object
 5   Length_of_Stay         3000 non-null   int64
 6   Previous_Admissions    3000 non-null   int64
 7   Comorbidities          2259 non-null   object
 8   Discharge_Disposition  3000 non-null   object
 9   Readmitted             3000 non-null   object
dtypes: int64(4), object(6)
memory usage: 234.5+ KB

In [7]:
df.describe()

         Patient_ID          Age  Length_of_Stay  Previous_Admissions
count   3000.000000  3000.000000     3000.000000          3000.000000
mean   11500.500000    54.029667       15.123667             4.461000
std      866.169729    20.155401        8.228301             2.864009
min    10001.000000    20.000000        1.000000             0.000000
25%    10750.750000    37.000000        8.000000             2.000000
50%    11500.500000    54.000000       15.000000             4.000000
75%    12250.250000    71.000000       22.000000             7.000000
max    13000.000000    89.000000       29.000000             9.000000

In [8]:
df.count()

Patient_ID               3000
Age                      3000
Gender                   3000
Admission_Type           3000
Primary_Diagnosis        3000
Length_of_Stay           3000
Previous_Admissions      3000
Comorbidities            2259
Discharge_Disposition    3000
Readmitted               3000
dtype: int64

## 📊 3. Exploratory Data Analysis (EDA)

In [10]:
df.isnull().sum()

Patient_ID                 0
Age                        0
Gender                     0
Admission_Type             0
Primary_Diagnosis          0
Length_of_Stay             0
Previous_Admissions        0
Comorbidities            741
Discharge_Disposition      0
Readmitted                 0
dtype: int64

In [11]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Admission_Type', 'Primary_Diagnosis',
       'Length_of_Stay', 'Previous_Admissions', 'Comorbidities',
       'Discharge_Disposition', 'Readmitted'],
      dtype='object')

In [12]:
df.shape

(3000, 10)

In [13]:
df.head()

,Patient_ID,Age,Gender,Admission_Type,Primary_Diagnosis,Length_of_Stay,Previous_Admissions,Comorbidities,Discharge_Disposition,Readmitted
0,10001,71,Male,Urgent,Pneumonia,4,5,3-4,Transferred,No
1,10002,34,Male,Emergency,Diabetes,21,8,NaN,Home,No
2,10003,80,Female,Urgent,Pneumonia,21,1,1-2,Transferred,No
3,10004,40,Female,Emergency,Pneumonia,8,2,1-2,Home,No
4,10005,43,Male,Elective,Stroke,25,8,5+,Transferred,No

In [14]:
df.tail()

,Patient_ID,Age,Gender,Admission_Type,Primary_Diagnosis,Length_of_Stay,Previous_Admissions,Comorbidities,Discharge_Disposition,Readmitted
2995,12996,68,Female,Urgent,Cancer,20,4,1-2,Expired,No
2996,12997,73,Male,Urgent,Heart Failure,15,7,1-2,Expired,No
2997,12998,29,Male,Urgent,Heart Failure,1,3,NaN,Expired,No
2998,12999,72,Male,Urgent,Diabetes,2,3,NaN,Expired,No
2999,13000,63,Male,Urgent,Pneumonia,8,6,NaN,Expired,No

In [15]:
df.isna().any()

Patient_ID               False
Age                      False
Gender                   False
Admission_Type           False
Primary_Diagnosis        False
Length_of_Stay           False
Previous_Admissions      False
Comorbidities             True
Discharge_Disposition    False
Readmitted               False
dtype: bool

In [16]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

## 📈 4. Model Training – Logistic Regression

In [18]:
x = df.drop("Readmitted", axis=1)  # Replace 'Adulteration' with your actual target column name
y = df["Readmitted"]

In [19]:
y

0       No
1       No
2       No
3       No
4       No
        ..
2995    No
2996    No
2997    No
2998    No
2999    No
Name: Readmitted, Length: 3000, dtype: object

In [20]:
for col in x.select_dtypes(include='object').columns:
    le = LabelEncoder()
    x[col] = le.fit_transform(x[col])

In [ ]:
df.hist(figsize=(10, 9), bins=20, edgecolor='black')
plt.suptitle('Feature Distributions', fontsize=16)
plt.show()

#### **Visualizes pairwise relationships**

In [ ]:
sample_df = df.sample(n=200, random_state=42)  # To reduce computation
sns.pairplot(sample_df, hue='Readmitted', diag_kind='kde', palette='husl')
plt.suptitle("Pairplot of Sample Features", y=1.02)
plt.show()

## 🧪 5. Train-Test Split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)

In [ ]:
LOR = LogisticRegression()
LOR

In [ ]:
LOR.fit(x_train, y_train)

## ✅ 6. Model Evaluation

In [ ]:
y_pred= LOR.predict(x_test)

In [ ]:
classification = classification_report(y_test, y_pred)

In [ ]:
acc =accuracy_score(y_test,y_pred)
acc

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

#### **Hyperparameter Tuning**

In [ ]:
param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear']
}

grid = GridSearchCV(LogisticRegression(max_iter=1000), param_grid, cv=5)
grid.fit(x_train, y_train)

print("Best Parameters:", grid.best_params_)

#### **Retrain with Best Params**

In [ ]:
best_model = grid.best_estimator_
y_pred_optimized = best_model.predict(x_test)

print("Optimized Accuracy:", accuracy_score(y_test, y_pred_optimized))

#### **Boxplots for numeric features**

In [ ]:
plt.figure(figsize=(15, 10))
num_cols = df.select_dtypes(include='number').columns
for i, col in enumerate(num_cols):
    plt.subplot(3, 4, i + 1)
    sns.boxplot(x=df[col], color='skyblue')
    plt.title(col)
plt.tight_layout()
plt.show()

#### **Count plots for categorical features**

In [ ]:
cat_cols = df.select_dtypes(include='object').columns
plt.figure(figsize=(15, 10))
for i, col in enumerate(cat_cols[:6]):  # show first 6
    plt.subplot(2, 3, i + 1)
    sns.countplot(data=df, x=col)
    plt.xticks(rotation=45)
    plt.title(f'Count Plot of {col}')
plt.tight_layout()
plt.show()

## 📉 7. Advanced Evaluation (Optional)

#### **Pie chart to visualize the distribution of hospital readmissions**

In [ ]:
data_counts = df['Readmitted'].value_counts()

plt.figure(figsize=(7, 7))
plt.pie(data_counts, labels=data_counts.index, autopct='%1.1f%%', colors=['blue', 'orange'])

plt.title("Hospital Readmission Distribution")

plt.show()

#### **Heatmap (if correlation applies)**

In [ ]:
if len(num_cols) > 1:
    plt.figure(figsize=(10, 8))
    sns.heatmap(df[num_cols].corr(), annot=True, cmap='coolwarm', linewidths=0.5)
    plt.title("Feature Correlation Heatmap")
    plt.show()

#### **Violin Plot : Displays the distribution of features across the target classes.**
- **The x-axis shows the readmission status (e.g., "Yes", "No", etc.).**
- **The y-axis shows the length of hospital stay.**
- **The width of each violin indicates the distribution density: wider = more data points.**
- **The white dot and thick bar inside the violin show the median and interquartile range (IQR).**

In [ ]:
plt.figure(figsize=(15, 8))
sns.violinplot(x='Readmitted', y='Length_of_Stay', data=df, palette='Set2')
plt.title("Violin Plot: Time in Hospital by Readmission Status")
plt.show()

#### **Kernel Density Estimation for continuous variable comparison.**

In [ ]:
plt.figure(figsize=(10, 6))
for label in df['Readmitted'].unique():
    sns.kdeplot(df[df['Readmitted'] == label]['Previous_Admissions'], label=f'Readmitted={label}')
plt.title("KDE Plot: Number of Lab Procedures")
plt.xlabel("Previous_Admissions")
plt.legend()
plt.show()

#### **Pie chart to visualize the proportion of different categories in the dataset.**

In [ ]:
labels = [ 'Admission_Type','Primary_Diagnosis', 'Length_of_Stay','Discharge_Disposition']
sizes = [30, 20, 25, 25] 
colors = ['lightblue', 'lightgreen', 'orange','red']
explode = (0, 0.1, 0,0)  

plt.figure(figsize=(7, 7))
plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=140, explode=explode)
plt.title('Category Distribution')
plt.show()

#### **Distribution of Target Variable (Readmitted or Not)**

In [ ]:
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=["Not Readmitted", "Readmitted"], yticklabels=["Not Readmitted", "Readmitted"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

#### **Bar Plot for Categorical Feature vs Target**

In [ ]:
plt.figure(figsize=(10, 6))
sns.barplot(data=df, x='Gender', y='Readmitted', ci=None, palette='mako')
plt.title("Average Readmission by Gender")
plt.show()